services:
  fastapi:
    build:
      context: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend/downloads:/app/downloads
    networks:
      - app-network

  server:
    build:
      context: ./server
    container_name: node_proxy
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3001:3000"  # Mapea localhost:3001 -> contenedor:3000
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
